name: Scheduled Monitor

on:
  schedule:
    - cron: '55 * * * *'  # This will run the job at 55 minutes past every hour

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring script
        run: |
          python main.py  # Replace with the actual script name
